// Generated by CoffeeScript 1.4.0
var addon_bar_button, data, network, panels, self, show_panel, tabs, widgets;

widgets = require('widget');

tabs = require('tabs');

self = require('self');

data = self.data;

panels = require('panel');

network = require('request');

show_panel = panels.Panel({
  width: 250,
  height: 400,
  contentURL: data.url("show.html"),
  contentScriptFile: data.url("show.js")
});

show_panel.port.on('init', function(image_element) {
  console.log("in init");
});

show_panel.port.on('picture-mouseup', function(mouse_event) {
  var field, _i, _len;
  console.log("in picture-mouseup");
  for (_i = 0, _len = mouse_event.length; _i < _len; _i++) {
    field = mouse_event[_i];
    console.log(field);
  }
});

show_panel.on('show', function() {
  console.log("in show");
  show_panel.port.emit("show");
});

addon_bar_button = widgets.Widget({
  id: "imgly-icon",
  label: "show image",
  contentURL: "http://img.ly/assets/favicon-a1b5a899dcd5f68a9feb9e80b4b63935.ico",
  panel: show_panel
});
